services:
  - type: web
    name: biztype32
    env: node
    plan: free
    buildCommand: npm install && npm run build && npm run seed
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: biztype-data
      mountPath: /opt/render/project/data
      sizeGB: 1
